### ISSUE TITLE
VRCPlates

### ISSUE THREAD

**Issue by ghost** [FSCodingWaifu/CVRMods#2]
could you make it so the plates toggle with the in game nameplates toggle
could you also make a version of the mod/option that adds the current VRC plates

**Comment by syscatFS** [comment]
The current VRChat Nameplates as well as 2019 will require asset recreations. Presently I only ever plan to make the 2019 ones, however, if there is enough demand I will think about it.

As for the nameplate toggles, I'm working on it. CoHTML is a pain to work with, so we'll see how long it takes.

**Comment by syscatFS** [comment]
The most recent release now hooks into the CVR Nameplate Settings.
